### ISSUE TITLE
Readme mentions unit conversion is easy, but no instructions ?

### ISSUE THREAD

**Issue by bobloadmire** [mjmccans/hassio-addon-airthings#14]
Thanks for the great add-on, it's really awesome. my only question is the read me mentions that unit conversion is really easy, but maybe I'm too dumb to figure out how to convert to pCi/L? I'm not seeing any options available.

**Comment by mjmccans** [comment]
I have not added unit conversion to the addon itself, and while it may be relatively easy to add nobody has asked for it yet (probably because the Airthings devices are not as popular in the U.S. where I understand the pCi/L unit is more prevalent). One option for now would be to add a template sensor to your Home Assistant configuration file along the lines of the following:

```
sensor:
  - platform: template
    sensors:
      radon_1_day_avg_pcil:
        value_template: >
          {% if not is_state("sensor.basement_office_radon_1_day_avg","unknown") %}
            {{ ((states.sensor.basement_office_radon_1_day_avg.state | float) / 37) | round(3) }}
          {% endif %}
        friendly_name: 'Basement Office Radon (1 day avg. pCi/L)'
        icon_template: mdi:radioactive
        unit_of_measurement: 'pCi/L'
```

The above assumes that the sensor coming from the addon is "sensor.basement_office_radon_1_day_avg" and you want 3 digits of the result (the "Round(3)"). You can try the above, modifying it as needed, and hopefully that gets you what you need. I am by no means an expert in Jinja2 or templating so feel free to correct the above or provide any improvements.
